### ISSUE TITLE
Delete Backups

### ISSUE THREAD

**Issue by Josexv1** [punitrathore/emacs.d#1]
You have a backbup folder with sensitive info. like **AWS secret keys**, and other stuff. You should never, ever upload backups to a public repository.

**Comment by punitrathore** [comment]
Whoa, thanks for letting me know!

**Comment by Josexv1** [comment]
No problem, just force a rollback and re-commit in order to delete the commit history.

**Comment by punitrathore** [comment]
Just curious, how did you stumble upon this repo?

**Comment by Josexv1** [comment]
I was reading an article about sensitive data leaked into github repos, and i just searched for some keywords like **access, key, secret, ssh** and turns out that there are lots of passwords and keys shared into github code.
